[package]
name = "wasmd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
varintrs = "0.2.0"
byteorder = "1.4.3"
thiserror = "1.0"
